### ISSUE TITLE
Browser cache not clearing with dev build

### ISSUE THREAD

**Issue by gaurav2887** [AngularClass/angular2-webpack-starter#1077]
I am using devtool: cheap-module-source-map in my dev build as mentioned in this project. 

Every time I deploy the app to aws, it requires me to do CTRL+F5(full cache refresh) on the browser and it does not pull latest changes on normal page refresh (F5). Is there any way to refresh the cache on F5 as users might not do CTRL+F5 in prod and will have issues.

**Comment by katallaxie** [comment]
The browser caches resources by default; also the HTTP Server sends information regarding the caching behavior in the browser. You should version your resources `?v=12345`, so that the browser fetches the most recent version and does not caches. Btw. you should allow to cache things, it's a better UX.
