### ISSUE TITLE
How to import Angular Material 2 in this webpack?

### ISSUE THREAD

**Issue by rafaelss95** [AngularClass/angular2-webpack-starter#1082]
I want to know how can I import Angular Material on this webpack. I already installed Angular Material with npm, and import everything, however I can't manage it to work.

Thanks in advance.

**Comment by dweitz43** [comment]
there is a branch specifically for material integration. there is also a pull request #1066 open to update that branch to the latest version of material

**Comment by rafaelss95** [comment]
Thanks for your answer @dweitz43. What's the branch specifically for material integration?

**Comment by dweitz43** [comment]
It's the material2 branch

**Comment by karcheng** [comment]
hi i am new to git. The material2 branch doesn't have changes made in #1066. How do get the code that was changed for pull request #1066.

**Comment by dweitz43** [comment]
@karcheng you could pull from the material2 branch of my fork https://github.com/dweitz43/angular2-webpack-starter/tree/material2

**Comment by vetik32** [comment]
did you remove `material2` branch (from your fork)? 😕

**Comment by dweitz43** [comment]
@vetik32 unfortunately i did as it had become very out of date with the master branch since the pull request had not been merged since it was created two weeks ago. i am not so sure why they might be reluctant to merge the pull requests, however i suppose i could just continue to keep the branch up to date on my fork without creating pull requests if there is enough interest.

**Comment by karcheng** [comment]
No, I didn’t remove the material2 branch. I am sorry if I did. Like I said, I am learning git. Please let me know if I did something wrong.

**Comment by d3viant0ne** [comment]
Closing this one. The material2 branch, although out of date is sufficient to add material2 to the advanced seed as is @dweitz43's fork.

**Comment by evanjmg** [comment]
+1 - if the material branch is removed. Remove it from the html, it's really confusing. If there is a working one, please post it here.

**Comment by holms** [comment]
It's removed thanks, now how the f... I can integrate materials2 in here? Whole internet is intergrating. materials2 with angular-cli, which is freaking annoying, because this webstarter is using webpack!! Can you please integrate bootstrap, and materials on separate branches for people..? What the point of this project if we can't even use UI frameworks with this starter???

**Comment by AyzPat** [comment]
Guys when include the material 2 the tabs css is not working in the file so do i need to use anything to make it work??
Also when I use the a utocomplete i get the originX error as in the link here-- https://github.com/angular/material2/issues/3176
