### ISSUE TITLE
Hi Patrick,  I have several days ago paid the bundle subscription to angularclass which is supposed to start end of august 2016, but did not get an answer or access to the courses?  Patrick, can you please clarify

### ISSUE THREAD

**Issue by rahulsingh-code** [AngularClass/angular2-webpack-starter#1160]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by joaogarin** [comment]
You should probably find another channel for this I guess..twitter / slack / website etc..?

**Comment by gdi2290** [comment]
Quality takes time. While starting the courses in the Master Bundle We realized the community was missing a ton of advanced content. This meant that we either would need to cover advanced topics within each course or start releasing our separate content to reference. A good exaof this is our current Fundamentals course which skips a lot of the conceptual topics since there's a ton of content already out there already. We provide a guided path of how to build an app in the real world. Following this teaching style we quickly realized all of the courses within the Master Bundle requires knowledge of advanced patterns which aren't covered anywhere online. We decided that we would have to create advanced content so we have something to point to as reference. We started by creating a Router course abd ab Advanced Components courses only to combine them into one course as Advanced. Right now anyone who bought the Master Bundle gets everything for free until we finish the courses. So that means everyone will get the complete path to becoming an expert at Angular 2. This is different from content release right now which doesn't provide a path because it simply takes more thought to create. We're also providing real world advanced patterns that leads to expert. Also the introduction of NgModule dramatically changed the way we should be architecting our applications so previously we had a great plan and progression on how to guide users to becoming experts. After NgModule we first had to figure out new patterns that developers should be doing and figuring out the correct approach. Because of that huge change we had to regroup and delay the release. If you followed our Fundamentals course then you would know that it was right before NgModule
