### ISSUE TITLE
Subscription 500$ paid Sept/2016 but no videos as of 10.11.2016

### ISSUE THREAD

**Issue by hansschenker** [AngularClass/angular2-webpack-starter#1164]
Hi Patrick,
I thought you are a sincere member of the javascript community!
How can let down people in such a unprofessional way.

Please behave like a professional and provide the promissed already paid content!

**Comment by paralin** [comment]
wat

**Comment by hansschenker** [comment]
Yes Christian,

it is sad but true!

regards
Hans

2016-11-13 1:29 GMT+01:00 Christian Stewart <notifications@github.com>:

**Comment by gdi2290** [comment]
We spoke via email and gave a preview of our current progress and a refund.

Quality takes time. While starting the courses in the Master Bundle We realized the community was missing a ton of advanced content. This meant that we either would need to cover advanced topics within each course or start releasing our separate content to reference. A good example of this is our current Fundamentals course which skips a lot of the conceptual topics since there's a ton of content already out there already. We provide a guided path of how to build an app in the real world. Following this teaching style we quickly realized all of the courses within the Master Bundle requires knowledge of advanced patterns which aren't covered anywhere online. We decided that we would have to create advanced content so we have something to point to as references. We started by creating a Router course and an Advanced Components courses only to combine them into one course as Advanced course to cover more content. Right now anyone who bought the Master Bundle gets everything for free until we finish the courses. So that means everyone will get the complete path to becoming an expert at Angular 2. This is different from content release right now which doesn't provide a path because it simply takes more thought to create. We're also providing real-world advanced patterns seen in large Angular 2 apps in production. Also, the introduction of NgModule dramatically changed the way we should be architecting our applications so previously we had a great plan and progression on how to guide users to becoming experts. After NgModule we first had to figure out new patterns that developers should be doing and figuring out the correct approach. Because of that huge change we had to regroup and delay the release. If you followed our Fundamentals course then you would know that it was right before NgModule
