### ISSUE TITLE
webworker support

### ISSUE THREAD

**Issue by gdi2290** [AngularClass/angular2-webpack-starter#125]
@matthewdenobrega I added your changes in the [webworker](https://github.com/AngularClass/angular2-webpack-starter/tree/webworker) and added you to the repo if you want to try out webworkers

**Comment by matthewdenobrega** [comment]
Thanks @gdi2290 - a couple of notes:
 - For the webpack dev server to work in webworkers you need this patch: https://github.com/webpack/webpack-dev-server/pull/309 - hopefully it will get merged into master soon
 - I don't think this is a good base for production apps yet, in part because the current router doesn't work in a web worker. This is being worked on this week - https://github.com/angular/angular/issues/3563
 - I'll update this branch when routing is working

**Comment by gdi2290** [comment]
thanks, I added you to the repo so you have write access. 
ya I forgot to mention the patch (I edited mine in node_modules too). The starter purposely does not have a production build but I agree with you that it's not ready yet

**Comment by gdi2290** [comment]
muli-environment support will be done via [universal-starter](https://github.com/angular/universal-starter) I'll close this for now and redirect people to universal starter after it's updated
