### ISSUE TITLE
TemplateURL usage

### ISSUE THREAD

**Issue by joaogarin** [AngularClass/angular2-webpack-starter#126]
Hello,

I am expermenting with the starterkit. I was wondering how to use templateURL, is there specific things I need to change or add in the webpack.config.js.

Can you point me in the right direction? In the readme it says  : 

How do I use moduleId with module.id in webpack?
Please use __filename if you must use templateUrl and styleUrls rather than webpack's module system

But it didnt really understand..sorry still pretty new to webpack.

Best regards

**Comment by dotcs** [comment]
One way to use files for the templates (instead of the inline-style) is to create HTML files and `require` them with the `to-string-loader`.

```javascript
@Component({
  selector: 'my-component',
})
@View(
    template: require('to-string!./my-component.html')
})
export class MyComponent {}
```

Webpack will require the file `my-component` and assign the output to the template of the view. Technically you are not using Angular's `templateUrl` here, but in fact it's more or less the same thing. 

On the plus side is that the HTML content is bundled via webpack and does not require an additional HTTP request. You don't have to bother where to put the files on your production environment, because they are bundled. On the negative side is that the bundle will include ALL templates you include in such a way - even if the user may not use all of them. So in very large projects, this might be an issue.

A working example can be found in one of my public repos: [cueonthespot-web](https://github.com/dotcs/cueonthespot-web)

**Comment by gdi2290** [comment]
@dotcs is correct. If we use templateUrl provided by angular then we lose out on some of the optimizations provided by webpack

**Comment by joaogarin** [comment]
Thank you for the explanation. its more clear now. I guess for what i want using the inline template or the approach you mention is more suitable to take advantage of webpack. its really just a small project to start getting familiar with angular2 and trying a couple of things.

Thanks for the great info and the nice repo;) Works perfectly

**Comment by gdi2290** [comment]
np, make sure you [:star:](https://github.com/AngularClass/angular2-webpack-starter/stargazers) the repo

**Comment by louisscruz** [comment]
When I attempt to use `template: require('to-string!./my-component.html')` I get the following error: "Cannot resolve module 'to-string'" Any idea what I'm doing wrong?

**Comment by gdi2290** [comment]
you can use the raw loader which is already set for html
https://github.com/AngularClass/angular2-webpack-starter/blob/master/webpack.config.js#L62

**Comment by louisscruz** [comment]
@gdi2290 Thank you! I was using an older version of the project. After cloning the latest, a lot has changed – glad to see the new file structure. Just starred the project by the way...

**Comment by richdyang** [comment]
@dotcs If I use template: require('./xx.html') to utilize the webpack bundle, how can I handle the performance issue in a big project, too many templates and too big bundle file.

**Comment by yjaaidi** [comment]
@richdyang @gdi2290 I just made a pull request to angular2-template-loader in order to be able to use a file-loader for templates : https://github.com/TheLarkInn/angular2-template-loader/pull/39

**Comment by ilkercat** [comment]
@richdyang Have a look at Donald Knuth's opionen to premature optimization. [http://wiki.c2.com/?PrematureOptimization](url)
