### ISSUE TITLE
About tree shaking...

### ISSUE THREAD

**Issue by mdelgadov** [AngularClass/angular2-webpack-starter#1331]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Just asking a question...

* **What is the current behavior?**

In the master branch AOT is configured and works very well.
But  the mentions to tree shaking are limited and not very clear.
Nevertheless, the size of the output in the current build:aot goes from 3,123 to 493 kb.

When I look in other sources for Tree shaking, it says that apparently needs a special configuration on tsconfig to use a different module management.

So my question is: Does the current version has Tree shaking or we can expect even smaller sizes when it becomes implemented?

That's all, small question....

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by colinskow** [comment]
Tree shaking is all setup in master and there's nothing else you need to do. `tsconfig.webpack.json` is set to export ES2015 modules which is what Webpack 2 needs for tree shaking. The `vendor.ts` file has been removed and all packages from inside `node_modules` will automatically be tree shaken put into the vendor bundle.

Note that tree shaking doesn't happen with CommonJS `require()` modules so only packages which use `import` will benefit.

**Comment by mdelgadov** [comment]
beautiful, thanks and closed!

**Comment by Ks89** [comment]
Very interesting. 

I have a theoretical question (because at the moment, tree-shaking documentation is impossibile to find on this planet :)), but I want to explain in a better way using a concrete example.

For instance, I implemented tree shaking in a personal project and I'm able to run and navigate into my application. Very well!

Before tree shaking, my vendor.ts was something like this:

```
// import angular
// import rxjs

// Third party opensource libraries
import 'angular2-image-popup';
import 'angular2-ladda';
import 'ng2-simple-page-scroll';
import 'angular2-recaptcha/angular2-recaptcha';
import '@ng-bootstrap/ng-bootstrap';
import 'ng2-validators';

// Other famous libraries
import 'jquery';
import 'lodash';
import 'bootstrap-loader'; // used to import bootstrap as scss

// use this if you want to see the spinner before angular's booting
import 'font-awesome/css/font-awesome.css';
// css to show a centered spinner before angular's booting
import '../src/loading.css';

import 'jquery-slimscroll';
```

With tree shaking, I haven't a vendor.ts file, so how angular2-image-popup, angular2-ladda and so on are imported?
For example, **my application is working, but I can't find bootstrap and the other libs.**

For sure some of them aren't es2015 ready, but where should I import these libs in my project (the structure is similar to this project)? I mean...**I want to run my application with all libs, also If they aren't shaken :)**

Thank u.

**Comment by colinskow** [comment]
@Ks89 you can put any global imports such as Boostrap into `app.module.ts`.

Any imports that are parsed through your entry point that are inside `node_modules` will automatically be extracted into a vendor bundle. You no longer need to declare them manually in `vendor.ts` since the process is automatic.

**Comment by Ks89** [comment]
@colinskow thank u, it's working :)
