### ISSUE TITLE
Fonts, url-loader, and AOT

### ISSUE THREAD

**Issue by bmayen** [AngularClass/angular2-webpack-starter#1406]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
I have fonts located under `/assets/fonts`. When I try to use one in CSS I get the following error:
```
ERROR in ./src/assets/fonts/OpenSans-Regular.ttf
Module parse failed: /angular2-webpack-starter/src/assets/fonts/OpenSans-Regular.ttf Unexpected character ' ' (1:0)
You may need an appropriate loader to handle this file type.
```
I add `url-loader` for font files and HMR and Prod builds work as expected. Fonts get inlined under a certain threshold and saved with a hash above this threshold. However, when running an AOT build, inlined fonts work but files which are expected to be saved externally are not created so I get 404s for `http://127.0.0.1:8080/fonts/629a55a7e793da068dc580d184cc0e31.ttf` 

* **What is the expected behavior?**
I would like to have AOT builds which save fonts separate from the bundle. Otherwise I'm forced to inline everything and bundle sizes are very large.

* **Please tell us about your environment:**

- Latest angular2-webpack-starter, osx, win WSL

**Comment by bmayen** [comment]
Ah, I was referencing my fonts with a relative path. If I change that reference to `/assets/fonts/...`, I no longer need to add url-loader and everything works by simply referencing copied fonts under `/assets/fonts/`. 

Would be curious to hear an explanation for this as I don't quite understand what's going on here, but this issue can be closed otherwise.

**Comment by d3viant0ne** [comment]
Completely valid usability issue, one of us will take a look at it this evening

**Comment by bmayen** [comment]
A little more insight into this. The solution I described above only works because root-relative paths cause css-loader to skip hashing those assets. So, for example, if I add `?root=/.` to css-loader, the css will be changed to point to `[hash].ttf`. Plain prod builds work as expected here: the fonts are copied with hashed filenames and the css is updated to point to them. However, in AOT builds, wile the css is updated, the actual hashed files are not being generated.

**Comment by bmayen** [comment]
Looks like the same issue here #1428

**Comment by shlomiassaf** [comment]
@bmayen the issue in #1428 happens on non-inlined assets within component templates/styles.

Are you loading fonts in component styles? bit excessive... if so turn `resourceOverride` off until the AOT plugin will handle assets.

Long story short, `resourceOverride` removes template/styles from `@Component` to remove space and let the AOT compiler handle them.
If you have resources in components then they won't get copied...

**Comment by bmayen** [comment]
Thanks for the feedback. 

Can you clarify what you mean by "If you have resources in components..."? Aren't all resources in components?

We have a _fonts.scss file which defines styles which point to different fonts under `/assets/fonts`. This gets imported into our app.scss which gets included in app.component.ts styleUrls with encapsulation set to NONE. This is excessive? Open to suggestions for a better approach here.

In my mind, we would ideally be able to include all assets in our component styles and they would all be hashed in prod builds regardless of relative or root-relative urls. Is there a reason we wouldn't want this?

**Comment by shlomiassaf** [comment]
> If you have resources in components...

Resources, such as jpeg, png, fonts etc... 

Usually, application wide resources (such as `_fonts.scss`) should be located in an application wide style sheet and not in a component specific style sheet.  
We have integrated global styles recently, see this [folder](https://github.com/AngularClass/angular2-webpack-starter/tree/master/src/styles)

Having said that, your can solve your issue but the problem remains, the `NgcWebpackPlugin` with AOT compilation ** and resourceOverride ** activated does not support the `file-loader` or any other loader that emits multiple files from a single source.

For example, a loader gets a CSS files as an input an emits the css file content + 1 JPEG file that it found in a `url('...')` reference.

The reason is simple, AOT compiler runs and passes templates/styles through webpack. Webpack does it's job, if `file-url` is activated it will replaces the content as normal.  
However, that is a different webpack and it only do loader chain so the files never get copied.

Next phase is bundling, again webpack (different instance) runs but this time all of those templates/styles are empty (`resourceOverride`) so hash files not copied.

If hashes are not created then the plugin that copies all asset folder cover up this issue, if hashes are created then that's a problem

This is a tricky issue, it involves a lot of webpack internals... handling cache and invalidation, making sure an asset that was hashed would be copied but it's origin wont... I will fix it...

**Comment by bmayen** [comment]
Ah, gotcha. Ok, thanks for the explanation. Makes things much clearer for us.

**Comment by shlomiassaf** [comment]
Please check version 1.2.0 of `ngc-webpack`, should solve your issue.

I'd appreciate if you can replay with the results.

**Comment by shlomiassaf** [comment]
See #1451

**Comment by bmayen** [comment]
Terrific! Will try this tonight. Thanks again!

**Comment by bmayen** [comment]
Works great! Closing this issue.

**Comment by shlomiassaf** [comment]
Thanks

**Comment by shlomiassaf** [comment]
FYI: With version 3.2.0 of `ngc-webpack` using `reousrceOverride` is no longer needed not recommended.

Just add the loader along with the plugin and everything should work.
