### ISSUE TITLE
Is it possible to update compiled css styles without refreshing page?

### ISSUE THREAD

**Issue by gudh** [AngularClass/angular2-webpack-starter#1457]
First of all, thanks for building this amazing starter, it helped me a LOT, thanks you!

**I'm submitting a ...**
[x] feature request

**What is the current behavior?**
For now, the angular app refreshes every time a .scss or .css file is changed

**What is the expected behavior?**
Ideally, styles files are recompiled and inject into page without refreshing the page 

**What is the motivation / use case for changing the behavior?**
Because for now, every page fresh takes me at least **5 seconds**, and gets longer as the app grows. 

I am writing a lot of scss styles for my angular2 app, I used to use GulpJS, which inject the new compiled css into the page in real time, done in **1 second** (There's no page refreshes). However for now I have to wait for at least **5 seconds** (page refreshes) every time I save my scss files.

**Please tell us about your environment:**

- Angular version: ^2.4.5
- Browser: [Chrome 55.0.2883.95 (64-bit)]

**Comment by zhekaus** [comment]
This is the major downside of Webpack comparing to well-created Gulpfile.js : it is much slower even if it does all its manipulation in memory. After even a tiny change it has to rebuild the bundle.

**Comment by gudh** [comment]
@zhekaus exactly!

There seems to be ways to do css HMR without refreshing page, I googled online, tried some solutions, not work. So I wonder if AngularClass team has any ideas on this.

**Comment by shlomiassaf** [comment]
@zhekaus @gudh it depends how you structure your app.

when you used Gulp I imagine you didn't do it on Angular 2 right? so instead of blaming webpack try to understand the environment :)

CSS in angular `@Component`s are not part of the global CSS you used to have in Gulp and that was loaded via an HTML link tag.

CSS that you attach to components is part of the bundle, if you refresh CSS the whole ngModule must refresh.

It is possible that the reloading can improve, but it will take time once people fully realise the process and webpack will adapt.

**Comment by bmayen** [comment]
@shlomiassaf, could we use ExtractTextPlugin to bundle all of the Component css as a separate css bundle loaded via link tag? Aside from one less network request, is there a benefit to having it all be part of the main js bundle? Or at least, could this be done for Dev builds to benefit from faster CSS reloads?

**Comment by gudh** [comment]
@shlomiassaf,  Thanks for the reply!

Actually, my css are all global instead of in angular `@Component`

So in my case, is it possible to reload without refreshing the page?
