### ISSUE TITLE
IE10 and IE11 support

### ISSUE THREAD

**Issue by kampdomoj** [AngularClass/angular2-webpack-starter#148]
I tried to run this application on different browsers. I noticed that it doesn't work on IE.
I posted a question on the Angular github page, and they say that es6-shim should be included to make it work on IE.

I checked in the history that es6-shim has been removed recently.

I tried to change my local copy and added es6-shim in package.json and in the angular2 webpack bundle, but that didn't help.

Please advice...

**Comment by gdi2290** [comment]
we switched to core-js which has more polyfills

**Comment by kampdomoj** [comment]
Okay... but what should I do to make this starter work in IE?
Just wait until the Angular2-team releases a version of angular that works properly with all browsers?

**Comment by gdi2290** [comment]
their ci suggest that it's suppose to work so it might be the tooling
[![Sauce Test Status](https://saucelabs.com/browser-matrix/angular2-ci.svg)](https://saucelabs.com/u/angular2-ci)

if you add es6-shim and replace core-js with it then it might work again assuming that was the problem https://github.com/AngularClass/angular2-webpack-starter/blob/2c8fface424f569bfded2d35369baad077d1fbc0/webpack.config.js#L30

if that doesn't work then you can also undo this change
https://github.com/AngularClass/angular2-webpack-starter/commit/2c8fface424f569bfded2d35369baad077d1fbc0
and include my version of `es6-shim ` in `src/public/lib`
https://github.com/AngularClass/angular2-webpack-starter/blob/5afffdb91b66c934203b5ceeb210ea7ec9de62e3/src/public/lib/es6-shim.js



can you also elaborate on the "doesn't work on IE" part? It might be my build system rather than angular2 so it's hard to tell what errors you're running into

**Comment by kampdomoj** [comment]
Hi, I have seen you updated your app to the beta version, and it works perfectly on all browsers. Of course :-)  
Thanks. Issue solved.

**Comment by gdi2290** [comment]
thanks for making an issue about it :+1: if you run into any more problems or have any suggestions feel free to open an issue
