### ISSUE TITLE
[AOT] File size is larger than prod one

### ISSUE THREAD

**Issue by pavillet** [AngularClass/angular2-webpack-starter#1520]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

It's a question

* **What is the current behavior?**

I just finished updating to aot and my code seems to works fine with npm run build:aot.
But I'm not sure I'm doing this right since the generated file is 3MB larger than the one generated with npm run build:prod ( so jit only )

Two questions then, is that normal ( and if not how can I reduce this size ) ? And do I have a way of knowing if i'm running the aot version ?

The steps I'm using : 

npm run build:aot:prod
npm run server:prod
 => File size is 5mo

npm run build:prod
npm run server:prod
 => File size is 1mo

Thanks 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

The aot bundle file should be smaller

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: Latest
- Browser: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Question posted on https://gitter.im/AngularClass/angular2-webpack-starter but no answer yet.

**Comment by shlomiassaf** [comment]
Hi,

Latest repo version, running `npm run build:aot:prod`:  
![image](https://cloud.githubusercontent.com/assets/5377501/22889574/4f6bb778-f212-11e6-90a6-f545aeb17416.png)

**Total folder size: 1M**

Latest repo version, running `npm run build:prod`:  
![image](https://cloud.githubusercontent.com/assets/5377501/22889593/5b9cfeee-f212-11e6-98e6-4c7216014768.png)

**Total folder size: 1.3M**

You might notice that the `main` file and `chunk` files are larger in `build:prod:aot` then in `build:prod`, this is perfectly normal since AOT produces more code.

The total amount is less in AOT since the compiler is not part of the bundle, you can see it in the size of the `vendor` bundle.

This also means that as your application grow, AOT will yield larger code since you add more AOT generated code but the compiler size is constant.

The angular team is working on reducing the emitted code, one of the upcoming feature for this is a new [View Engine](https://github.com/angular/angular/issues/14013) that will reduce bundle size but will slightly effect performance (it's always a tradeoff)

I see no issue here, try to start from scratch, you probably changed something

**Comment by pavillet** [comment]
@shlomiassaf Thank you so what you are saying is that on a large application main will be larger ? This could be my problem then since the app is rather large
