### ISSUE TITLE
Bootstrap JS - Modal - Property 'modal' does not exist on type 'JQuery'

### ISSUE THREAD

**Issue by jayapalt** [AngularClass/angular2-webpack-starter#1523]
Hi I've configured Bootstrap 3 in Angular2-webpack-starter based on this link `https://github.com/sasidhar/angular2-webpack-starter` .

Everything is working fine except  below error shows in cmd line

[at-loader] Checking finished with 1 errors
[at-loader] src\app\app.component.ts:33:23
    TS2339: Property 'modal' does not exist on type 'JQuery'.

error causing line is 
jQuery('#myModal').modal('show');

Do we want to import Bootstrap.js anywhere or anyother dependency issue ?

**Comment by shlomiassaf** [comment]
So many things are done wrong here, I don't know where to start...

Since this is not the place for support questions, but for actual issues, please ask on the relevant channels.

   - Don't use jQuery
   - Don't use `bootstrap.js` use the relevant angular 2 replacement library
 
Other then that, learn about `@ViewChild` / `@ViewChildren` and don't use jQuery to get dom elements.

The way you write the code, you better of not use angular at all... use jQuery.

**Comment by ademidun** [comment]
Try this [SO answer](https://stackoverflow.com/a/41390347/5405197):
`npm install -D @types/bootstrap`

**Comment by trulyhuman** [comment]
> Try this [SO answer](https://stackoverflow.com/a/41390347/5405197):
> `npm install -D @types/bootstrap`

This solution worked for me. thanks a lot for sharing this solution It saved my day
