### ISSUE TITLE
CommonsChunkPlugin in webpack.common.js has syntax error

### ISSUE THREAD

**Issue by vincent-cm** [AngularClass/angular2-webpack-starter#1632]
new CommonsChunkPlugin({
        name: 'vendor',
        chunks: ['main'],
        minChunks: module => /node_modules/.test(module.resource)
      }),

The last config "minChunks: module => /node_modules/.test(module.resource)" seems breaking javascript syntax. When using IDE like webstorm, the code after this config is reported broken.

**Comment by tytskyi** [comment]
@vincent-cm it is correct. The code is reported as broken by WebStorm because you have ECMAScript 5.1 (or another version) as your target version in Settings.

Go to `Settings -> Languages & Frameworks -> JavaScript`
Select `JavaScript language version` as `ECMAScript 6`

Re-open WebStorm, observe that errors gone.

Please close the issue, once you got it to work
