### ISSUE TITLE
Recommend merging with this massive new Angular 2 app

### ISSUE THREAD

**Issue by born2net** [AngularClass/angular2-webpack-starter#187]
Angular 2 is still young and finding examples online can be hard... So I decided to develop a "real" app... I am Happy to announce the release of ng2Boilerplate. This application was developed from scratch with Angular 2 and it's awesome.

Checkout the app: http://ng2.javascriptninja.io/
checkout the source: https://github.com/born2net/ng2Boilerplate

I recommend we marge angular2-webpack-starter with ng2Boilerplate
ng2Boilerplate uses async loading but can be modified to use Webpack as well

Regards,

Sean - http://DigitalSignage.com

**Comment by gdi2290** [comment]
thanks, I checked it out. I slowly made the app and examples larger but that ended up confusing more people which is why the example app currently is trivial. I separated the examples that use to live in this repo out (they still need to be updated) so I can't merge anything more without more content about the repo
