### ISSUE TITLE
WebPack2?

### ISSUE THREAD

**Issue by jgodi** [AngularClass/angular2-webpack-starter#220]
Are there any plans to use webpack 2?

**Comment by gdi2290** [comment]
yeah I can add it as a branch. I'm holding off only because there are more plugins available for 1.x

**Comment by jgodi** [comment]
I am just curious on the performance improvements and that. Thank you! :+1:

**Comment by gdi2290** [comment]
there are some problems since we need to tell TypeScript not to compile the es6 modules (to get the benefits) or Compile to ES6 then get Babel to compile to ES5 or use a commonjs to es6 convert plugin. There won't be ny performance improvements unless the module/code is using ES6 modules so it can do tree shaking

**Comment by ansarizafar** [comment]
@gdi2290  Any progress on this?

**Comment by fxck** [comment]
out of the currently used plugins, which are not ported to webpack2?

**Comment by gdi2290** [comment]
I have a Webpack 2 version that's experimental at the moment
https://github.com/gdi2290/angular2-webpack2-starter

**Comment by gdi2290** [comment]
one of the benefits is the use of typescript for the webpack config

**Comment by sp90** [comment]
Do we have a timeline on when this is getting this project?

**Comment by fxck** [comment]
https://github.com/AngularClass/angular2-webpack-starter/issues/843
