### ISSUE TITLE
Typings main.d.ts not referenced in tsconfig.json?

### ISSUE THREAD

**Issue by andreialecu** [AngularClass/angular2-webpack-starter#244]
Was this switched to use typings recently?

I got a lot of errors during the typescript compilation step until I added `"./typings/main.d.ts"` to `"filesGlob"` and/or `"files"` in `tsconfig.json`

Shouldn't it be there or is there something else wrong in my environment?

**Comment by abdulhaq-e** [comment]
Same here. Perhaps it is due to an update of the typescript compiler because I've only noticed this recently, now, anything not included in ```filesGlob``` will not be add to ```files``` in ```tsconfig.json```. So ```tsconfig.json``` that is currently in the repo will not be the same after compilation because [L13](https://github.com/AngularClass/angular2-webpack-starter/blob/master/tsconfig.json#L13) will be deleted.

**Comment by andreialecu** [comment]
If you're using Atom, I think it overwrites the `"files"` section on every save. So it needs to be in `"filesGlob"` as well.

**Comment by andreialecu** [comment]
See: https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#filesglob
