### ISSUE TITLE
`typings install` Throws Error

### ISSUE THREAD

**Issue by datatypevoid** [AngularClass/angular2-webpack-starter#278]
Fresh clone of repo(Win10, latest node, latest npm) attempting to run `typings install` after running `npm install` and am getting the following error:

![Error](https://i.gyazo.com/389a61c201e1575a84d1d9263e913dcc.png)

**Comment by datatypevoid** [comment]
So sorry to waste your time. `npm run typings-install` worked fine as mentioned at the top of the README

**Comment by gdi2290** [comment]
`npm run typings-install` uses the local version (the one installed and lives in `node_modules`) of typings so you probably need to update your global version `npm install -g typings` cc @blakeembrey

**Comment by blakeembrey** [comment]
@datatypevoid It sounds more like you've recently updated to NPM v3. Since NPM v3 creates a flat structure, it assumes certain things about the module installation layout that currently exists. If you're combining a previous NPM v2 install with v3, this is a pretty common issue I've seen pop up (because it assumes it exists at the top level from a different dependency, but NPM v2 structure was no flat so it actually doesn't exist).

Does that sound like your problem? If so, just run a re-install over the modules to make sure the structure is correct.
