### ISSUE TITLE
Lint doesn't not check files

### ISSUE THREAD

**Issue by RemKolomna** [AngularClass/angular2-webpack-starter#378]
If I run **npm run lint** I got messages:

Linting 0 files
Done with 0 failures.

How to fix it?

**Comment by samvloeberghs** [comment]
Well basically that's because the linting tool doesn't support the filesGlob in tsconfig.json. You have to use a tool that generates the files list in tsconfig.json. For example tsconfig-glob: https://www.npmjs.com/package/tsconfig-glob

I've encountered this problem last week as well, but did not have the time yet to create a PR.

Grtz

**Comment by dsebastien** [comment]
Actually filesGlob does not exist in TypeScript (yet), it was only
introduced/supported by the Atom TS plugin.

For my projects, I usually am fine with just the exclude property;
basically I just let TS include everything except what I have in my exclude
array:
https://github.com/dsebastien/angularjs-webpack-starter/blob/master/tsconfig.json

**Comment by gdi2290** [comment]
can someone make a PR

**Comment by samvloeberghs** [comment]
on my way :) @gdi2290

**Comment by dsebastien** [comment]
IMHO, the correct place to fix this is tslint itself. They have an issue there: https://github.com/palantir/tslint/issues/858

That would probably remove the need for using tsconfig-lint

**Comment by samvloeberghs** [comment]
also check this one: 
https://github.com/palantir/tslint/issues/1012

**Comment by sasidhar** [comment]
#289

**Comment by louisscruz** [comment]
I just cloned the latest and tried to lint. No success.

The current `lint` runs `./node_modules/.bin/tslint src/**/*.ts`. What can be done to fix this?

**Comment by dsebastien** [comment]
FYI tsconfig-lint (npmjs.com/package/tsconfig-lint) is now able to find files using tsconfig.json even if files or filesGlob are not use (see https://github.com/wjohnsto/tsconfig-lint/issues/3). In my case I only specify excludes and that works well. IMHO filesGlob shouldn't be used as its still not officially supported by TS (AFAIK).

0.8.0 also includes a change I've submitted to have it use an external config file (e.g., tslint.json).

Thus until https://github.com/palantir/tslint/issues/858 is fixed, I think this is a good solution.

**Comment by gdi2290** [comment]
`npm run lint works` you can try it out yourself by writing code that doesn't fit the code style

**Comment by louisscruz** [comment]
Something must be wrong with my configuration. Can't get lint to run for the life of me. Hopefully if someone else's this problem, they'll respond here.

**Comment by samvloeberghs** [comment]
@gdi2290, it still does not output the same results.

`npm run build:prod` gives errors on tslint
`npm run lint` doesn't

**Comment by dsebastien** [comment]
The solution I've describe above works, try it out.

**Comment by louisscruz** [comment]
@samvloeberghs In my case the fix was simple. In package.json change `"lint": "./node_modules/.bin/tslint src/**/*.ts"` to `"lint": "./node_modules/.bin/tslint 'src/**/*.ts'"`. The missing quotation marks were established in [this commit](https://github.com/AngularClass/angular2-webpack-starter/commit/1563944036b4f2c80ca0ddca93487b197f7bf231) and fixed in [this commit](https://github.com/AngularClass/angular2-webpack-starter/commit/d4d2c04b6f1c1f78dc7170cd37adba70dfc2bf41).

**Comment by samvloeberghs** [comment]
I have a clean install, with those fixes already incorporated

**Comment by StormToft** [comment]
@louisscruz thanks! that fix worked for me.
