### ISSUE TITLE
Reflect.getMetadata

### ISSUE THREAD

**Issue by mbcooper** [AngularClass/angular2-webpack-starter#464]
I pulled the latest and am porting an app that we wrote with a version of the starter app in December.  So much has changed!

The core.js defines a version of "Reflect" that does not have getMetadata.

How would I include that as an overload of the Reflect method?  Everything seems so tightly wired!

**Comment by zloirock** [comment]
> The core.js defines a version of "Reflect" that does not have getMetadata.

`core-js` contains `Reflect.getMetadata` O_o

**Comment by gdi2290** [comment]
Thanks for creating the issue. the issue you're looking for is https://github.com/zloirock/core-js/issues/152. Reflect does include getMetadata and I can understand the confusion you may have since it wasn't documented in the repo. I'm going to close this issue but if you like it would help everyone else if we updated the FAQ to mention this. If you could edit the readme to include this then that would be great. thanks!

**Comment by zloirock** [comment]
It's already documented [here](https://github.com/zloirock/core-js#pre-stage-0-proposals).

**Comment by mbcooper** [comment]
I am still stuck.  In the current polyfill.ts, we 
`import 'core-js';`
which builds typings for the "old" Reflect definition.

The Reflect typing in typings/core-js/index.d.ts show Reflect without "getMetaData".

Do I have to add a specific import in polyfill, AND add a typing in typings.json?
I'm trying all sorts of ways to do this, and I cannot seem to get teh right definition of "Reflect" to my code.
@zloirock - I see it in your library, but my question is how to integrate it into the starter kit

**Comment by zloirock** [comment]
Looks like need update type definitions for `core-js` because [current definitions for `0.9.7` version](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/core-js/core-js.d.ts#L1) - May 2015. I'm not an expert in TypeScript, so feel free add PR. Or, I think, in addition, you can use definitions for `reflect-metadata` package.

**Comment by gdi2290** [comment]
I'll reopen and fix the type definitions

**Comment by gdi2290** [comment]
thanks for the issue. fixed via https://github.com/AngularClass/angular2-webpack-starter/commit/820531520314f095443dce3db6946df04c859e7d
