### ISSUE TITLE
please provide a minimal version of angular2-webpack-starter without the bloat

### ISSUE THREAD

**Issue by ehartford** [AngularClass/angular2-webpack-starter#483]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
feature

* **What is the current behavior?**
it is too big, bloated, bulky.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
I want a version of angular2-webpack-starter that is minimal.  It should have only angular2 and webpack, not 4 million other things.  (especially test.  really don't need any test harnesses built into "how to angular2 webpack" setup)
All test code and libraries should be removed.
All unneeded files should be removed.

* **What is the motivation / use case for changing the behavior?**
so I won't be confused and bedazzled by things I don't need to learn Angular2 and Webpack.

* **Please tell us about your environment:**
angular2-webpack-starter

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by datatypevoid** [comment]
Strip it out yourself and start a new repo. Your tone seems a bit entitled.

**Comment by gdi2290** [comment]
you're looking for https://github.com/angular/angular2-seed

**Comment by alvipeo** [comment]
I actually moved all my code to mgechev seed and it has this out of memory problem. But what's cool is that it's more strict on typescript. Really cool! Can we have the same in here?

**Comment by gdi2290** [comment]
@alvipeo how is it more strict on typescript?

**Comment by alvipeo** [comment]
It shows unused vars, more strict on types, doesn't allow untyped vars, etc. I actually just spent an hour fixing these errors.

**Comment by gdi2290** [comment]
that's just tslint though :/

**Comment by alvipeo** [comment]
Right. I copied tslint.json from seed to my proj (based on this nice repo) and it doesn't give any warnings/errors when type is not specified, for example. Then I reverted back to this repo tslint.json - same thing... Also, no sign of linting with 'npm run lint'.

So what I like with angular2-seed is with this code:
```
it("upload small file", inject([AsyncTestCompleter, Http, IlgAzureUploadService], (async: AsyncTestCompleter, http,
        uploadSvc: IlgAzureUploadService) => {
...
```
I get an error something like http doesn't have type defined. This really helps with RxJS chain of operators when it difficult sometimes to see what you got inside of a particular operator.

**Comment by spock123** [comment]
As someone else stated, this repo is not for newbies, there are lots and lots of technologies and concepts involved. 

If you want a simple example with just Ng2 and Webpack, I really think there are other and better seeds out there. 

But this seed is by far the best and closest to a "real world" setup and I very much appreciate it. 

We can't have it all..

Personally, what I do is that I base my projects around this seed. Then I manually remove or change the things that suit my project best. I've learnt a ton just understanding the different part of this project.

You really shouldn't use stuff like this without at least understanding what's going on. And it's a great excercise to use this project as a "starter" (hense the project name) and then do your own modifications. It's a relative simple matter to remove the stuff you don't need, and in the proces learning about the stuff.

Just my opinion of course.

**Comment by alvipeo** [comment]
I've been with this repo since alpha 46 and it's been really good overall. My personal opinion there shouldn't be material included but that's fine. It's easy to remove.

Overall, at the end of the day we'll get ng2 cli with way more simple building process and tools. It's overengineered now.

So, fine with me.

**Comment by user414** [comment]
I agree with @alvipeo, I don't believe material should be included and that's when I decided to track both angular2-seed and this one and use a hybrid of both. I like the prod/dev config of this repo and the fact that config files are separated, but use the package.json from the seed and add dependencies that I need instead of like before using this one and removing. Overall, I don't think we can have a one size fits all. Nonetheless, I think removing material from this one and adding a prod/dev config to seed might be overall beneficial.

**Comment by gdi2290** [comment]
the conclusion is this repo without protractor (e2e), karma (spec), and removing all the helper tasks in package.json

**Comment by user414** [comment]
@gdi2290 :-), yes impossible to cater to everyone. Then perhaps the only thing we can do is make sure we keep the filename, custom typings come to mind, and directory structure similar so it is easier to track multiple repo at once and have an hybrid solution.

**Comment by gdi2290** [comment]
I'm up for a hybrid solution but I need to know what that is

**Comment by user414** [comment]
@gdi2290 other people would have to chip in, myself I find it works fairly well as is tracking both repository as remote. Perhaps making sure the naming is consistent, like custom-typings.d.ts in one vs typings.d.ts and the entry points are the same like app.ts in one vs main.browser.ts in the other. Since when I merge with git if the name/location is not the same it's not as smooth. Also maybe using a webpack.common that's in common with both repo might be helpful, and using helper.js in both to calculate the root in webpack. In the end I would aim for as little difference between the two repos as necessary. However, all of this is just little things. Wouldn't want to add extra work for just my own preference. While I'm at it thanks for those seeds repo. It saves quite a bit of time, especially during the development cycle where updating between alphas/betas can at time be like a mine field.

**Comment by alvipeo** [comment]
I think the only fat is material. I personally use bootstram, others might use semantic ui or anything else. Other then that, it's a good repo and I actually like it because or all testing features it has.

**Comment by ajoslin** [comment]
Most of the bloat is angular2 itself, just remove that.

Would save a lot of kilobytes.

**Comment by gdi2290** [comment]
Andrew troll for dayz, tree shaking and precompile will help with the "bloat" in terms of file size. you can see in the weekly meetings for Angular that the file size for hello world is smaller than Angular 1
https://docs.google.com/document/d/150lerb1LmNLuau_a_EznPV1I1UHMTbEl61t4hZ7ZpS0/mobilebasic

**Comment by datatypevoid** [comment]
I love this framework and really would hate to see anything removed, other than Material, as seems the common consensus.

**Comment by datatypevoid** [comment]
People learning to use advanced JS frameworks are going to use all of these things in any position of professional capacity, so they shouldn't be scared of learning how to use the tooling provided. I tell this to my colleagues all the time.

**Comment by chriscurnow** [comment]
I'll chime in and say I love this framework as well. I was a complete novice to Webpack and Typescript and only slightly more than a novice with Angular2 when I started using this framework. Over all the other resources out there that I have found helpful in particular areas, this is the one that I would always base a new project on _[grammar pedants, I know the are just having to get used to the split _infinitive]__I wouldn't change anything here. I'm not sure if I will use material but its great to have it hear so I can have a look at it with almost no effort at all. The advanced tooling sometimes takes a bit of learning time but I'm so glad I persevered with it. There's still heaps in this repo that I don't understand yet but its great that it's there and pretty much works out of the box so I can use it without understanding it yet.
If anyone wants a stripped down version it would be easy enough to fork the repo and strip out everything they don't want. It's not like buying a car where you walk in and say I want that one. Whichever way you go, you need to do the work to et up to speed.

**Comment by IAMtheIAM** [comment]
I would recommend making SASS/SCSS integrated out of the box, and also Hot Module Replacement should be loaded by default with "start" instead of "start:hmr". I don't see any reason to not use HMR.

**Comment by Luchillo** [comment]
Why isn't this closed already?

To add to the discussion, to date (21/06/2016) this repo has HMR, app-shell and post app-shell fetching of routes implemented.

I personally have a fork working with scss, and i think it does should be implemented by default.

I personally use PrimeNG since is more production ready than Material 2, i think the theme library should be deleted and let the dev add the prefered one since there's a lot of spread in this field.

**Comment by Jensiator** [comment]
https://github.com/Jensiator/minimal-angular2-webpack-seed. I have don it and its pretty minimal. Even got a sharedmodule in it
