### ISSUE TITLE
Firefox JSON.parse bug

### ISSUE THREAD

**Issue by doxiaodong** [AngularClass/angular2-webpack-starter#513]
Error message: `EXCEPTION: Error: Uncaught (in promise): JSON.parse: unexpected character at line 4 column 1 of the JSON data`

my Firefox version is 45.0.1

And it looks good on Safari, Chrome, Edge

Online test: https://new.darlin.me

code: https://github.com/doxiaodong/darlin-angular2

thx

**Comment by MarkPieszak** [comment]
This isn't an issue with the Starter, you're using `JSON.parse()` in a few locations (https://github.com/doxiaodong/darlin-angular2/search?utf8=%E2%9C%93&q=JSON.parse) you probably have malformed data in the localStorage you're trying to retrieve.

When doing JSON.parse() from localStorage you usually want to do a try/catch so this doesn't happen. Also if the data isn't "parse-able" it will error out, why you want this.

````
try {
     var result = JSON.parse( /* whatever */ );
} catch (ex) {

}
````

**Comment by doxiaodong** [comment]
@MarkPieszak , I don't think so. It caused by res.json().  [https://	
o4vwdjxrs.qnssl.com/QQ20160426-0.png](https://	
o4vwdjxrs.qnssl.com/QQ20160426-0.png)

**Comment by akyataapp** [comment]
@MarkPieszak, how did you solve this? I get the error* below when I run in Firefox 49.0.2 and its caused by error.json() when I click on main.client.js. 

* error:

vendor_2d674efc492a0b6a2255</</</Json</Json.parse@http://localhost:3931/dist/vendor.js:51204:45
vendor_2d674efc492a0b6a2255</</</Body</Body.prototype.json@http://localhost:3931/dist/vendor.js:51930:25
HttpClient</HttpClient.prototype.handleServerErrorInHttpResponse@http://localhost:3931/dist/main-client.js:506:36
HttpClient</HttpClient.prototype.getAll/<@http://localhost:3931/dist/main-client.js:481:106
vendor_2d674efc492a0b6a2255</SafeSubscriber</SafeSubscriber.prototype.__tryOrUnsub@http://localhost:3931/dist/vendor.js:12052:14
vendor_2d674efc492a0b6a2255</SafeSubscriber</SafeSubscriber.prototype.error@http://localhost:3931/dist/vendor.js:12013:22
vendor_2d674efc492a0b6a2255</Subscriber</Subscriber.prototype._error@http://localhost:3931/dist/vendor.js:11957:10
vendor_2d674efc492a0b6a2255</Subscriber</Subscriber.prototype.error@http://localhost:3931/dist/vendor.js:11931:14
XHRConnection/this.response</onLoad@http://localhost:3931/dist/vendor.js:52265:22
vendor_2d674efc492a0b6a2255</</</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3931/dist/vendor.js:64355:22
vendor_2d674efc492a0b6a2255</</</NgZone</NgZone.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onInvokeTask@http://localhost:3931/dist/vendor.js:18306:33
vendor_2d674efc492a0b6a2255</</</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3931/dist/vendor.js:64354:22
vendor_2d674efc492a0b6a2255</</</Zone$1</Zone</Zone.prototype.runTask@http://localhost:3931/dist/vendor.js:64244:29
ZoneTask/this.invoke@http://localhost:3931/dist/vendor.js:64425:29

**Comment by doxiaodong** [comment]
@akyataapp , do you use django restframework. some rest framework will response html file when direct request with url([https://api.darlin.me/links/](https://api.darlin.me/links/)), and it should response json by ajax, but firefox not. The way to workaround is add json response like [https://api.darlin.me/links/?format=json](https://api.darlin.me/links/?format=json). Good luck

**Comment by doxiaodong** [comment]
@akyataapp , if else, you'd better check `JSON.parse()` in your code.

**Comment by akyataapp** [comment]
@doxiaodong, thanks for your answer. I added accept header in the request and that solved my problem.

We use webpack and Angular 2. Now I have another issue with Safari... The struggle continues :-)

**Comment by doxiaodong** [comment]
@akyataapp, may i help?
