### ISSUE TITLE
Package.json: why dependencies?

### ISSUE THREAD

**Issue by spock123** [AngularClass/angular2-webpack-starter#714]
* **I'm submitting a ...**
[x ] question about the decisions made in the repository

* **What is the current behavior?**
The package.json file lists project dependencies. 
I noticed that a lot of the "project" packages, for example @angular/*  are  listed in the dependencies section.

I assume that when a project is built, all dependencies are put into the bundle files.
Therefore I would assume that all the files in the "dependencies" section really should be in the "devDependencies" section.

Let's for example say that you want to add a node backend (which is reasonable to think). 
You would install packages for the backend, and when you deploy the application you would copy your backend source to the destination server, and then run "npm install --production"

This would effectively install all the @angular/* packages in the production environment. A behaviour you don't want. Npm install --production installs all packages listed in the "dependencies" section.

So my question is:
Is there something I've completely missed - or should we not move all packages into the "devDependencies" section?

If not, how would you distinct packages to be installed in a production environment, when adding a node backend?

Cheers, guys, really appreciate this project, it has helped me tremendously in setting up the exact environment I need for my projects.

**Comment by Luchillo** [comment]
Hi, i think is more about concept than about actual use, off course you can put `@angular` dependencies in dev since most users just install in production by uploading the bundled files and installing the server deps.

The concept i talk is that devDeps are the deps you need during development (mostly webpack, browserify, gulp...) and in normal deps goes the ones your app really use (like @angular/core) so it's about stating in the package that deps are the ones your app requires and devDeps are the ones you use to bundle, compile or deploy your app.

**Comment by spock123** [comment]
I understand this - however once you try to setup a node backend in the same project, you'll be in trouble.

This is mostly and information to newbies: if you use this excellent repo as a starter for your project, and you also need a backend as part of the project, do yourself a favor and move all dependencies to the "devDependencies" section.

Otherwise you end up installing a lot of modules in your production environment that you won't need.

I will close this issue now ;)
