### ISSUE TITLE
<% if (webpackConfig.htmlElements.headTags) etc

### ISSUE THREAD

**Issue by alvipeo** [AngularClass/angular2-webpack-starter#762]
Hi,

haven't looked at this repo for a while. Just cloned it and run, got this:

>><% if (webpackConfig.htmlElements.headTags) { %> <%= webpackConfig.htmlElements.headTags %> <% } %> 

on the top, and this:

>><% if (webpackConfig.metadata.isDevServer) { %>  <% } %> 

at the bottom.

Node 6.1.3

**Comment by alvipeo** [comment]
Just checked yesterday, these artifacts disappeared. Closing.

**Comment by supermarcos** [comment]
I know it is closed already but I will put my discover that, believe it or not (I still can hardly believe it), if you are on a Windows machine the problem is how you get to the path where your app is... I will explain myself:
If you have in D:\Projects\project_whatever your project and you go `cd d:`, then `cd project`... and so on, that will break webpack, but if you go `cd D:` then `cd Project` it will work!
Webpack will break if you don't follow exactly the same case. As simple and stupid as that...
Hopefully this helps somebody with the same problem in the future.

**Comment by tedvanderveen** [comment]
#https://github.com/Microsoft/vscode/issues/9448

**Comment by tedvanderveen** [comment]
I believe this is related: Microsoft/vscode/issues/#9448
