### ISSUE TITLE
Run type type information loss

### ISSUE THREAD

**Issue by asgerjensen** [AngularClass/angular2-webpack-starter#80]
Hi,

I'm not sure if this belongs here, or in angular2 proper, but I noticed that the types that are placed on stuff isn't used at runtime, which can lead to some pretty confusing situations.

Example:
```typescript
/// <reference path="../../../../typings/_custom.d.ts" />

/*
 * Angular 2
 */
import {Component, View, Directive, FormBuilder, Inject, Attribute}  from 'angular2/angular2';

/*
 * Directives
 * angularDirectives: Angular's core/form/router directives
 * appDirectives: Our collection of directives from /directives
*/

import {APP_DIRECTIVES} from '../../../directives/directives';


@Component({
  selector: 'productlist-filter',

})
@View({
  directives: [ APP_DIRECTIVES ],
  template : `<select (change)="onChange($event.target.value)">
                     <option value="4">4</option>
					 <option value="8">8</option>
			</select>`,
})
export class Example1 {
  private _value : number;
  constructor(  )
  {
	  this._value = 4;
	  let tmpValue : number = this._value + 5;
	  console.log("Test 1, ", (tmpValue )); // writes "Test 1, 9" in the log
  }
  
  onChange(newValue : number) {
	  this._value = newValue;
	  let tmpValue : number = this._value + 5;
	  console.log("Test 2 ", (tmpValue )); // writes "Test 2, 85" in the log because this._value is suddenly a string
	  
  }
  
}
```

**Comment by gdi2290** [comment]
this is a browser thing where the type is probably a string so you would need to convert it via `this._value = Number(newValue);`. In TypeScript the types are removed when your code is compiled.

**Comment by dotcs** [comment]
Typescript is a typed superset of JavaScript that compiles to plain Javascript. In the example above Typescript assumes that `newValue` is a number. Whenever Typescript can check the type, it will do it for you. So Typescript would raise an error if you would try to do something like:

    constructor() {
        this.onChange('abc');
    }

    onChange(newValue: number) {
        // ...
    }

Unfortunately the component template is a string, which is only rendered at runtime. Because of this, Typescript does not now about your `onChange` call. Because Typescript compiles to plain Javascript, there is no way to do the type checking during runtime.

So yes, this is a problem. The only way to handle these kind of problems that I know is to do some additional type checking inside the function and be super careful about the arguments if Typescript can't do the proper checks for you.

To convert to a number you can always do

    onChange(newValue: number) {
          console.log(+number * 3);
    }

The unary plus operator enforces conversion to a number (see [4.14.2 The +, –, and ~ operators](http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.pdf)).

**Comment by gdi2290** [comment]
@dotcs is correct in explaining how typescript works. if you need runtime type checks then you can check out this repo made by an angular core team member
https://github.com/vsavkin/RuntimeTypeChecks
If you have any more issues feel free to open another one or comment here
