### ISSUE TITLE
Question : The file head-config.common.js is not watched for changes ?

### ISSUE THREAD

**Issue by StefH** [AngularClass/angular2-webpack-starter#888]
**I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] question

It seems that the file **head-config.common.js** is not watched by **tsc** or **webpack**, so if you make a change in this file, you have to do a `npm start`.

Is there a better way to fix this ?

**Comment by IAMtheIAM** [comment]
That's because its inside of webpack options, and webpack options are not watched for changes. Any change to webpack config will require relaunching the `webpack-dev-server' or a recompile using `webpack` CLI. 

I don't know if what you're asking is possible with webpack since it isn't designed to watch it's own config for changes.

**Comment by StefH** [comment]
OK, thanks for details.
