### ISSUE TITLE
material branch

### ISSUE THREAD

**Issue by kodeine** [AngularClass/angular2-webpack-starter#912]
material branch so behind? any updates possible?

**Comment by dweitz43** [comment]
I have been working on trying to get the material2 branch up to date, I am currently experiencing some issues loading all of the styles successfully in the production build. I was able to load the tooltip styles successfully, and I think it would be possible to use that same method to load all of the styles for the rest of the components, but I am working on trying to implement a cleaner solution. If you're interested, you can check the material2 branch of my fork to see the progress I have made in bringing it up to date. I plan to submit a pull request once I can figure out the cleanest way to implement the material components

**Comment by kodeine** [comment]
@dweitz43 thank you i'll try your repo for now.

**Comment by kodeine** [comment]
@dweitz43 your branch run without errors so far =)
btw do you know any material2 form app or something i can quickly use to make a signup form?

**Comment by dweitz43** [comment]
@kodeine indeed it appears that everything functions correctly in development mode...running the application in production mode is where i experience the issues. so if you just need for dev, i think it works.

as far as a material2 form app or something, i am not really sure, i havent done too much with that using rc.5 yet. i think the best idea would be to check out the official angular docs on forms

**Comment by MangeshPimpalkar** [comment]
+1

**Comment by dweitz43** [comment]
#914

**Comment by dweitz43** [comment]
#915

**Comment by ajitsonlion** [comment]
i have tried integrating material to master branch, in prod material was not working, disabling the mangling in prod build however worked.

**Comment by dweitz43** [comment]
@ajitsonlion indeed there is apparently a bug in rc.5 that can cause the build to crash, and setting mangle to false can fix that. The pr I submitted includes this

**Comment by msegers** [comment]
I'm amazed this hasn't been updated yet, I guess we should just use the master and add material ourselves?

**Comment by kodeine** [comment]
@msegers i agree with you, a lot has been changed in master but material2 branch has been neglected. maybe we need contributors who could keep material2 branch up to date?

**Comment by dweitz43** [comment]
This is something I have usually worked on with each rc increase. Sometimes my pr's for it have been neglected for a while, sometimes the master has been in a constant state of change to the point where bringing material up to date required maybe more effort than it was worth. I decided to wait until the final release and the subsequent master update to bring this branch up to date. Unfortunately I have been very busy since the final release as I have recently moved to a new country and have been working through several bureaucratic processes, studying to learn the local language, and keep my software dev skills sharp as I search for a job as well. However, I should have time tomorrow and the rest of this weekend to try to get this branch up to date again

**Comment by kodeine** [comment]
@dweitz43 thanks a lot for all your efforts! much appreciated!

**Comment by dweitz43** [comment]
#1041 here is the pr i just made to bring the material2 branch up to date. no idea if/when it will get merged, but i have run the hmr dev server and the prod build, as well as karma and e2e testing, and all seems to work. tslint fails due some problem in the one line rule, there is an open issue on that here #992

**Comment by ebeal** [comment]
This should be up to date now.
