### ISSUE TITLE
AngularClass Subscription paid but no courses available!!!

### ISSUE THREAD

**Issue by HansS** [AngularClass/angular2-webpack-starter#938]
Hi Patrick,
i appreciate Angularclass very much.
I have several days ago paid the bundle subscription to angularclass which is supposed to start end of august 2016, but did not get an answer or access to the courses?

Patrick,
can you please clarify

**Comment by gdi2290** [comment]
Hey @HansS sorry we weren't more transparent and thanks for purchasing the Master Bundle. We have the courses on a new schedule that is not reflected on the website and the order might change up a bit. This is mostly due to fit Angular 2's release which is very soon and due to the recent changes in `2.0.0-rc.5`. We thought it would be better if we recreate the courses using the new approach after Angular 2 is released. The delay of the reactive course is mostly my fault going back and forth with @Hendrixer on if we should teach our new reactive architecture that we have, or to use the [angular2-observe-decorators](https://github.com/AngularClass/angular2-observe-decorators), or to focus only on reactivity and state management (our original plan). We were also thinking about if we should teach more RxJS or move that into the Modern JavaScript course or provide that as a mini-course. We decided to stick with our original plan because the observe-decorators is teaching a new way to manage your app with my own proposed spec that might change if it's merged with the Angular codebase. Our new reactive architecture has all of the features that everyone is talking about (rxjs, redux, sagas, effects) plus a ton of features that no-one is talking about (past/present/future states, interop, priority rendering, isolated loops, hot module replacement, webworkers, universal) and would need a few more iterations to unify the whole story. A lot of sugar is needed before we release it to make the API more intuitive and will most likely be a free course.

**Comment by smith64fx** [comment]
![image](https://cloud.githubusercontent.com/assets/3246782/18165238/6bee40c8-7044-11e6-971f-d70a617bf4ec.png)

**Comment by smith64fx** [comment]
Just kidding ^^

**Comment by yshterev** [comment]
Hi @gdi2290  - I also pre-ordered the Master Bundle. Any rough estimate when any of the courses will be available?
